-- SQL 문제 풀기 → 월요일까지 풀어서 제출하기....

-- 1. 
SELECT DISTINCT(DEPTNO) AS DEPTNO
FROM EMP;

--2.
-- ||
SELECT ENAME||' 사원의 담당 직무는 '||JOB||' 입니다.' AS NAME_JOB
FROM EMP;
-- CONCAT
SELECT CONCAT(ENAME, CONCAT(' 사원의 담당 직무는 ',CONCAT(JOB, ' 입니다.')))
FROM EMP;

--3.
SELECT SAL, SAL+1000,SAL-200, SAL*2, SAL/2
FROM EMP;

--4. 
SELECT SAL, COMM, SAL+NVL(COMM,0) AS TOTAL
FROM EMP;

--5.
SELECT ENAME, EMPNO FROM EMP;

--6
SELECT ENAME, EMPNO, JOB, SAL FROM EMP;

--7
SELECT DEPTNO, DNAME FROM DEPT;

--8. 
SELECT * FROM DEPT;

--9. 
SELECT * FROM EMP;

--10.
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = 10;

--11.
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO <> 10;

--12.
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL >= 1500;

--13.
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE ENAME ='SMITH';

--14.
SELECT EMPNO, ENAME, JOB FROM EMP WHERE JOB ='SALESMAN';

--15.
SELECT EMPNO, ENAME, JOB FROM EMP WHERE JOB != 'CLERK';

--16. 
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > '1982-01-01';

--17. 
SELECT EMPNO, ENAME, DEPTNO, JOB
FROM EMP
WHERE DEPTNO = 10 AND JOB = 'MANAGER';

--18.
SELECT EMPNO, ENAME, SAL, HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-12-31'
AND SAL >= 1500;

--19.
SELECT EMPNO, ENAME, DEPTNO, SAL
FROM EMP
WHERE DEPTNO = 20 AND SAL >=1500;

--20. 
SELECT EMPNO, ENAME, MGR, JOB
FROM EMP
WHERE MGR = '7698' AND JOB = 'CLERK';

--21. ?? 급여?
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE SAL BETWEEN 1000 AND 2000;

--22. 
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE DEPTNO IN (20, 30);

--23.
SELECT EMPNO, ENAME, JOB
FROM EMP
WHERE JOB IN ('CLERK','SALESMAN','ANALYST');

--24.
SELECT EMPNO, ENAME
FROM EMP
--WHERE EMPNO NOT IN ('7499','7566','7839');
WHERE EMPNO NOT IN (7499,7566,7839);

--25.
SELECT ENAME, EMPNO
FROM EMP
WHERE ENAME LIKE 'F%';

--26.
SELECT ENAME, EMPNO
FROM EMP
WHERE ENAME LIKE '%S';

--27.
SELECT ENAME, EMPNO
FROM EMP
WHERE ENAME LIKE '%A%';

--28.
SELECT ENAME, EMPNO
FROM EMP
WHERE ENAME LIKE '_A%';

--29. 
SELECT ENAME, EMPNO
FROM EMP
WHERE LENGTH(ENAME) = 4;

--30.
SELECT EMPNO, ENAME, COMM
FROM EMP
WHERE COMM IS NULL;

--31.
SELECT ENAME, EMPNO
FROM EMP
WHERE MGR IS NULL;

--32.
SELECT EMPNO, ENAME, SAL
FROM EMP
ORDER BY SAL;

--33.
SELECT EMPNO, ENAME, SAL
FROM EMP
ORDER BY EMPNO DESC;

--34;
SELECT EMPNO, ENAME
FROM EMP
ORDER BY ENAME ASC;

--35.
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
ORDER BY HIREDATE DESC;

--36.
SELECT ENAME, EMPNO, SAL
FROM EMP
WHERE JOB = 'SALESMAN'
ORDER BY SAL;

--37.
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-12-31'
ORDER BY EMPNO DESC;

--38.
SELECT ENAME, SAL, COMM FROM EMP ORDER BY COMM;
SELECT ENAME, SAL,  NVL(COMM,0) AS COMM FROM EMP ORDER BY COMM;

--39.
SELECT ENAME, SAL, COMM FROM EMP ORDER BY COMM DESC;
SELECT ENAME, SAL,  NVL(COMM,0) AS COMM FROM EMP ORDER BY COMM DESC;

--40. 
SELECT (SAL-2000) AS SUB, ABS(SAL-2000) AS ABS
FROM EMP;

--41. 
SELECT SAL, SAL-TRUNC(SAL*0.15) AS RESULT
FROM EMP
WHERE SAL >= 1500;

--42.
SELECT SAL, SAL+ROUND(SAL*0.2,-2) AS RISED
FROM EMP
WHERE SAL <=2000;

--43
SELECT TRUNC(SAL,-2) AS TRUNC_SAL FROM EMP;

--44
SELECT EMPNO, ENAME, DEPTNO,
DECODE ( DEPTNO,
                10, '인사과',
                20, '개발부',
                30, '경영지원팀',
                40, '생산부'
            ) AS DEPT_NAME
FROM EMP;

-- 45.
SELECT EMPNO, ENAME, JOB, SAL, 
CASE 
WHEN JOB = 'CLERK' THEN TRUNC(SAL*1.1)
WHEN JOB = 'SALESMAN' THEN TRUNC(SAL*1.15)
WHEN JOB = 'PRESIDENT' THEN TRUNC(SAL*2)
WHEN JOB = 'MANAGER' THEN TRUNC(SAL*1.05)
WHEN JOB = 'ANALYST' THEN TRUNC(SAL*1.2)
END AS SAL_RESUTL
FROM EMP;

--46.
SELECT EMPNO, ENAME, JOB, SAL,
CASE 
WHEN SAL < 1000 THEN 'C등급'
WHEN SAL BETWEEN 1000 AND 2000 THEN 'C등급'
ELSE 'A등급'
END AS SAL_GRADE
FROM EMP;

--47.
SELECT EMPNO, ENAME, JOB, SAL,
CASE 
WHEN SAL < 1000 THEN SAL*2
WHEN SAL BETWEEN 1000 AND 2000 THEN SAL*1.5
ELSE SAL*3
END AS SAL_RESULT
FROM EMP;
