

desc member;

DELETE FROM member;
COMMIT;

drop table member;

CREATE TABLE MEMBER(
  ID NUMBER(4) CONSTRAINT TABLE1_PK PRIMARY KEY  , 
  NAME VARCHAR2(20) , 
  EMAIL VARCHAR2(100) , 
  HP VARCHAR2(13),
  REGDATE DATE
);


-- INSERT INT TABLE 명 () VALUES ();
-- DELETE FROM TABLE 명 WHERE 조건; 
-- UPDATE TABLE 명 SET 컬럼 명 WHERE 조건;
 
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL,'PARK','JI@MASE.COM','01049005899',SYSDATE);


select * from member;
UPDATE MEMBER SET NAME = 'TEST01', HP = '01098765432' WHERE ID = 1002;

SELECT * FROM MEMBER WHERE ID = 1004;

-- no 시퀀스 자동입력 prm, id/ pw/ name/email/hp/regdate date
-- 삭제, 업데이트는 ID.[PASS확인
-- 스윙으로 구현
DROP TABLE MEMBER;

CREATE TABLE NEWMEMBER(
  NO NUMBER(4) CONSTRAINT TABLE1_PK PRIMARY KEY  ,
  ID VARCHAR2(20) , 
  PW VARCHAR2(20) , 
  NAME VARCHAR2(20) , 
  EMAIL VARCHAR2(20) , 
  HP VARCHAR2(20),
  REGDATE DATE
);

INSERT INTO NEWMEMBER
VALUES (SEQ_MEMBER.NEXTVAL,'TEST','1234','TEST_NAME','J@MAIL.COM','01012345678',SYSDATE);

SELECT * FROM NEWMEMBER;