--- SELECT
--- INSERT UPDATE DELETE  -----  DML 데이터 수정

-- 테이블 삭제
DROP TABLE DEPT_TEMP;

-- 테이블 복사
CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;  -- TABLE 전체 복사
    
-- 테이블 껍데기복사
CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT WHERE 1=0;  -- TABLE 껍데기만 복사 ( 다른조건 쓰면 만족하는거만 가져옴 )

SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP;

-- 입력 // 행 추가     INSERT INTO 테이블 이름 ( 추가 할 열 제목 ) VALUE (추가 할 값);
--                                추가 열 생략하면 값 생략 가능 ( NULL 처리 ) 
--                                추가 열 지정 했으면 VALUE 값 무조건 입력//
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (50,'DATABASE','SEOUL');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (60,'JAVA','BUSAN');

INSERT INTO DEPT_TEMP
VALUES (70,'NETWORK','DANGSAN');


SELECT * FROM EMP;
SELECT * FROM EMP_TEMP;
CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP;

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9997,'PARK','CLERK',NULL, '22/01/18', 3000, 300, 50);

INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (9996,'PARK','CLERK',NULL, TO_DATE('01/18/2022','MM/DD/YYYY'), 3000, 300, 50);


SELECT E.EMPNO, E.ENAME, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND GRADE = 1;


INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)   

--- 서브쿼리 작성할때는 VALUES 를 쓰지 않음 / 데이터 타입도 동일하게..
(SELECT E.EMPNO, E.ENAME,E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO

FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE = 1);

SELECT * FROM EMP_TEMP;

-- 업데이트
CREATE TABLE DEPT_TEMP02
    AS SELECT * FROM DEPT; 
    
SELECT * FROM DEPT_TEMP02;

UPDATE DEPT_TEMP02
SET LOC = 'SEOUL',
    DNAME = 'DATABASE'
WHERE DEPTNO = 40;

ROLLBACK;
COMMIT;

--2500 이하는 COMM 50
SELECT * FROM EMP_TEMP;

UPDATE EMP_TEMP
SET COMM = 50
WHERE SAL <= 2500;

--DELETE ------------

DELETE FROM EMP_TEMP
WHERE JOB = 'CLERK';

--30번 부서 GRADE =3 인 경우

DELETE FROM EMP_TEMP
WHERE EMPNO IN (
                SELECT EMPNO
                FROM EMP_TEMP E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND S.GRADE = 3
                AND E.DEPTNO = 30 
                );


-- INSERT INT TABLE 명 () VALUES ();
-- DELETE FROM TABLE 명 WHERE 조건; 
-- UPDATE TABLE 명 SET 컬럼 명 WHERE 조건;

