-- DML --- INSERT UPDATE DELETE ( COMMIT / ROLLBACK )  COMMIT 이 되어야 제대로 적용
-- DDL --- TABLE 만들기..   - 만들면 바로 적용 

DROP TABLE EMP_DDL;

CREATE TABLE TABLE1 (
  EMPNO VARCHAR2(4) NOT NULL, 
  ENAME VARCHAR2(10),
  JOB   VARCHAR2(9),
  MGR   NUMBER(4),
);

CREATE TABLE EMP_DEPT_DDL
AS SELECT E.EMPNO, E.ENAME, E.MGR, E.HIREDATE, E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE 1=0;

SELECT * FROM EMP_DEPT_DDL;
DROP TABLE EMP_DEPT_DDL;

DROP TABLE EMP_ALTER;

CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

-- TABLE 변경 (추가)--
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

-- 컬럼 지우기
ALTER TABLE EMP_ALTER
DROP COLUMN HP;

-- 컬럼 이름 바꾸기
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

-- 컬럼 타입 바꾸기
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

---- TABLE 생성은 CREATE 수정은 ALTER

-- TABLE 이름바꾸기
RENAME EMP_ALTER TO EMP_RENAME;

DESC EMP_ALTER; 
 -- 변경되어 존재X
DESC EMP_RENAME; 
-- 이름 변경되어 정상 작동

-- TABLE 삭제하기
DROP TABLE EMP_RENAME;

-- 데이터 삭제
SELECT * FROM EMP_ALTER;

TRUNCATE TABLE EMP_ALTER;
  -- 데이터 정보 삭제됨.. 틀은 그대로






