--9장 풀이
--1문

SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE JOB = (
                SELECT JOB 
                FROM EMP 
                WHERE ENAME = 'ALLEN'
            )
            AND E.DEPTNO = D.DEPTNO;
--
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO 
AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN' );            
 
            
--2문            
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

SELECT E.EMPNO, E.ENAME, D.DNAME, 
        TO_CHAR(E.HIREDATE,'YYYY-MM-DD') AS HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL > (SELECT TRUNC(AVG(SAL)) FROM EMP)
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY SAL DESC, E.EMPNO;


--3문

SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.DEPTNO = 10
AND JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO =30)
;
-- SELECT JOB FROM EMP WHERE DEPTNO =30;  30 부서의 직업군..

-- 4문
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN')
AND E.SAL BETWEEN S.LOSAL AND S.HISAL  -- GRADE 정보를 필터링
ORDER BY E.EMPNO
;

-- 다중행으로 풀기 → 서브쿼리값이 여러개 인 경우!!
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL  -- GRADE 정보를 필터링
AND E.SAL > ALL (SELECT SAL FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY E.EMPNO
;

-- SALESMANS 최고급여
SELECT * FROM EMP;
SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN';

-- 부서번호 20 사원의 급여에서 해당하는 JOB 의 평균급여의 차이..
-- 1.사원급여 - JOB의 평균급여 = 스칼라..

SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, 
        (SELECT E.SAL - TRUNC(AVG(SAL)) FROM EMP EE WHERE E.JOB = EE.JOB GROUP BY JOB ) AS AVG_SAL_DIFF
FROM EMP E
WHERE DEPTNO = 20
;

-- 2.JOB 별 평균급여
SELECT TRUNC(AVG(SAL)) FROM EMP GROUP BY JOB;

-- 그대로  넣으면 JOB이 동일하지 않아도 잡혀서 오류

SELECT JOB, TRUNC(AVG(SAL)) AS AVG
FROM EMP
WHERE DEPTNO = 20
GROUP BY JOB
;
