-- 13장 실습

--1문
--생성
CREATE TABLE EMPIDX
AS SELECT * FROM EMP;
--확인
SELECT * FROM EMPIDX;
-- INDEX 생성
CREATE INDEX EMPIDX_EMPNO ON EMPIDX( EMPNO );
--INDEX 확인
SELECT * FROM USER_IND_COLUMNS;

--TEACHER
SELECT * FROM EMPIDX;
SELECT * FROM EMP;

SELECT * FROM USER_INDEXES
WHERE INDEX_NAME = 'EMPIDX_EMPNO';

--2문
-- 생성
CREATE VIEW EMPIDX_OVER15K
AS (
        SELECT EMPNO,ENAME,JOB,DEPTNO, SAL, NVL2(COMM,'O','X') AS COMM 
        FROM EMPIDX
        WHERE SAL > 1500
    );
    
--확인
SELECT * FROM EMPIDX_OVER15K;

-- 3문
-- DEPTSEQ 생성
CREATE TABLE DEPTSEQ
AS SELECT * FROM DEPT;
-- 확인
SELECT * FROM DEPTSEQ;
-- 시퀀스 생성
CREATE SEQUENCE SEQ_DEPTSEQ_DEPTNO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE;

-- 3-3 
INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPTSEQ_DEPTNO.NEXTVAL,'DATABASE','SEOUL');

INSERT INTO DEPTSEQ(DEPTNO, DNAME,LOC)
VALUES (SEQ_DEPTSEQ_DEPTNO.NEXTVAL,'WEB','BUSAN');

INSERT INTO DEPTSEQ(DEPTNO, DNAME,LOC)
VALUES (SEQ_DEPTSEQ_DEPTNO.NEXTVAL,'MOBILE','ILSAN'); 

        
-- 확인
SELECT * FROM DEPTSEQ;




