-- 14 장 제약조건
CREATE TABLE TABLE_NOTNULL (
        LOGIN_ID        VARCHAR2(20) NOT NULL,
        LOGIN_PWD   VARCHAR2(20) NOT NULL,
        TEL VARCHAR2(20)
);

DESC TABLE_NOTNULL;

-- NULL 값을 넣으려고 할 경우
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD,TEL)
VALUES ('TEST_ID_01', NULL,'010-0000-1111');
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD,TEL)
VALUES ('TEST_ID_01','','010-0000-2222');

-- 정상값 입력할 경우
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD,TEL)
VALUES ('TEST_ID_01', '1234','010-0000-3333');
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGIN_PWD,TEL)
VALUES ('TEST_ID_01','5678','010-0000-4444');

SELECT * FROM TABLE_NOTNULL;

SELECT OWNER, CONSTRAINT_NAME, TABLE_NAME FROM USER_CONSTRAINTS;

 --  입력기준을 NOT NULL로 수정.   기존데이터에 NULL 이 있으면 적용X & 오류 발생함!
ALTER TABLE TABLE_NOTNULL
MODIFY (TEL NOT NULL);

ALTER TABLE TABLE_NOTNULL
MODIFY (TEL CONSTRAINT TABLE_NOTNULL_TEL_NOTNULL NOT NULL);

SELECT * FROM TABLE_NOTNULL;

-- 걸려있는 제약조건 제거
ALTER TABLE TABLE_NOTNULL
DROP CONSTRAINT TABLE_NOTNULL_TEL_NOTNULL;


CREATE TABLE TABLE_UNIQUE(
    LOGIN_ID VARCHAR2( 20 ) UNIQUE,
    LOGIN_PWD VARCHAR2( 20 ) NOT NULL,
    TEL VARCHAR2(20)
    );
    
INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)
VALUES ('TEST01','1234','000-1111-2222');
INSERT INTO TABLE_UNIQUE (LOGIN_ID, LOGIN_PWD, TEL)   --- NULL 값은 허용함
VALUES (NULL,'5789','000-1111-2222');

SELECT * FROM TABLE_UNIQUE;

DROP TABLE TABLE_PK;
CREATE TABLE TABLE_PK( 
    LOGIN_ID VARCHAR2( 20 ) PRIMARY KEY, -- UNIQUE & NOT NULL
    LOGIN_PWD VARCHAR2(20),
    TEL VARCHAR2(20)
);

INSERT INTO TABLE_PK (LOGIN_ID, LOGIN_PWD, TEL) 
VALUES ('TEST01','1234','000-1111-2222');
INSERT INTO TABLE_PK (LOGIN_ID, LOGIN_PWD, TEL) 
VALUES ('TEST01','5678','000-1111-2222');
INSERT INTO TABLE_PK (LOGIN_ID, LOGIN_PWD, TEL) 
VALUES (,'5678','000-1111-2222');


---- FOREIGN KEY  -----------------------------------------------------

SELECT * FROM EMP;

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES  (1234, 'HONG', 'CLERK', 6789, SYSDATE, 2100, NULL, 50);

SELECT * FROM DEPT;

INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (50, 'WEB', 'BUSAN');

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('DEPT', 'DEPNO');

DROP TABLE DEPT_FK;
DROP TABLE DEPT_FK CASCADE CONSTRAINTS;
DROP TABLE EMP_FK CASCADE CONSTRAINTS;

CREATE TABLE DEPT_FK (
    DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(20)
);

CREATE TABLE EMP_FK (
    EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(20),
    JOB VARCHAR2(20),
    MGR VARCHAR2(20),
    HIREDATE DATE,
    SAL NUMBER( 7,2 ),
    COMM NUMBER( 7,2 ),
    DEPTNO NUMBER( 2 ) CONSTRAINT EMPFK_DEPTNO_FK05 REFERENCES DEPT_FK ( DEPTNO )
);


INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1236, 'PARK', 'CLERK', 6789, SYSDATE, 2100, NULL, 20);

SELECT * FROM DEPT_FK;


---- CHEAK  -- 입력규칙 설정하기.
DROP TABLE TABLE_CHECK;
CREATE TABLE TABLE_CHECK (
    LOGIN_ID    VARCHAR2(20) CONSTRAINT TB_CHECK_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) CONSTRAINT TB_CHECK_LOGINPWD_CH CHECK(LENGTH(LOGIN_PWD) > 3),
    TEL VARCHAR2 (20)
);

INSERT INTO TABLE_CHECK        -------------------  정상입력
VALUES ('TEST_ID_01','1234','010-1111-0051');
INSERT INTO TABLE_CHECK        -------------------  규칙 위반 오류.. (3글자 이상,)
VALUES ('TEST_ID_03','123','010-1111-0051');

SELECT * FROM TABLE_CHECK;

---DEFAULT  // 기본값 설정하기..
DROP TABLE TABLE_DEFAULT;
CREATE TABLE TABLE_DEFAULT(
    LOGIN_ID    VARCHAR2(20) CONSTRAINT TB_DEFAULT_LOGINID_PK PRIMARY KEY,
    LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
    TEL VARCHAR2 (20)
);

INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL)
VALUES ('TEST_ID_02', '010-2222-0051');

SELECT * FROM TABLE_DEFAULT;