DROP TABLE TEMP;

CREATE TABLE TEMP(
    COL01 VARCHAR2(20),
    COL02 VARCHAR2(20)    
);

INSERT INTO TEMP VALUES ('002','두번째 데이터');

SELECT * FROM TEMP;

GRANT SELECT ON TEMP TO TEST_USER;
GRANT INSERT ON TEMP TO TEST_USER;

REVOKE SELECT, INSERT ON TEMP FROM TEST_USER;

SELECT * FROM TEST_USER.TEMP;

INSERT INTO TEST_USER.TEMP VALUES ('003','세번째 데이터');