CREATE TABLE TEMP(
    COL01 VARCHAR2(20),
    COL02 VARCHAR2(20)    
);


SELECT * FROM TEMP;
INSERT INTO TEMP VALUES ('002','TEU02 데이터');

SELECT * FROM SCOTT.TEMP;

INSERT INTO SCOTT.TEMP VALUES ('003','TEU03 데이터');

GRANT SELECT ON TEMP TO SCOTT;
GRANT INSERT ON TEMP TO SCOTT;
GRANT SELECT, INSERT ON TEMP TO SCOTT;