-- 15강 문제풀이

-- SYS계정에서  // 계정 생성 AND 워크시트 권한주기
CREATE USER PREV_HW IDENTIFIED BY ORCL;
GRANT CREATE SESSION TO PREV_HW;

--SCOTT 계정에서 // 권한 주기
GRANT SELECT ON EMP TO PREV_HW;
GRANT SELECT ON DEPT TO PREV_HW;
GRANT SELECT ON SALGRADE TO PREV_HW;

---PREV_HW 계정에서 //  조회
SELECT * FROM SCOTT.EMP;
SELECT * FROM SCOTT.DEPT;
SELECT * FROM SCOTT.SALGRADE;

--SCOTT 계정에서 // 권한 뺏기
REVOKE SELECT ON SALGRADE FROM PREV_HW;