--CHAP 06Q

--1ANS
SELECT 
EMPNO, 
RPAD(SUBSTR(EMPNO,1,2),LENGTH(EMPNO),'*') AS MASKING_EMPNO,
ENAME,
RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >=5 AND LENGTH(ENAME) < 6 ;

--2ANS
SELECT EMPNO, ENAME, SAL,
TRUNC(SAL/21.5,2) AS DAY_PAY,
ROUND((SAL/21.5)/8,1) AS TIME_PAY
FROM EMP;

--2-2  원화로 바꾸기. 
SELECT EMPNO, ENAME, SAL,
TO_CHAR(TRUNC(SAL/21.5,2)*1187.41,'L999,999.00') AS DAY_PAY,
TO_CHAR(ROUND((SAL/21.5)/8,1)*1187.41,'L999,999.0') AS TIME_PAY
FROM EMP;


--3ANS
SELECT EMPNO,ENAME, --COMM FROM EMP;
TO_CHAR(HIREDATE,'YYYY/MM/DD') AS HIREDATE,
TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'),'YYYY-MM-DD') AS R_JOB,
NVL(TO_CHAR(COMM),'N/A') AS COMM
--CASE
--WHEN COMM IS NULL THEN 'N/A'
--ELSE TO_CHAR(COMM)
--END AS COMM
FROM EMP;

--3-2
SELECT EMPNO,ENAME, --COMM FROM EMP;
TO_CHAR(HIREDATE,'YYYY/MM/DD') AS HIREDATE,
TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'),'YYYY-MM-DD') AS R_JOB,
CASE
WHEN COMM IS NULL THEN 'N/A'
WHEN COMM IS NOT NULL THEN TO_CHAR(COMM)
END AS COMM
FROM EMP;


--4ANS
SELECT EMPNO,ENAME, MGR, 
CASE 
WHEN MGR IS NULL THEN '0000'
WHEN SUBSTR(MGR,1,2)=75 THEN '5555'
WHEN SUBSTR(MGR,1,2)=76 THEN '6666'
WHEN SUBSTR(MGR,1,2)=77 THEN '7777'
WHEN SUBSTR(MGR,1,2)=78 THEN '8888'
ELSE TO_CHAR(MGR)
END AS CHG_MGR
FROM EMP;