-- DATE 함수
SELECT SYSDATE AS NOW, 
SYSDATE - 1 AS YESTERDAY,
SYSDATE + 102 AS FUTURE
FROM DUAL;


SELECT SYSDATE AS NOW,
       ADD_MONTHS(SYSDATE,3)
       FROM DUAL;
       
SELECT * FROM EMP;
SELECT ADD_MONTHS(HIREDATE,120) AS ANNYVERSERY FROM EMP;

--40년 안된사람.
SELECT ENAME, EMPNO, HIREDATE, SYSDATE FROM EMP;
SELECT ENAME, EMPNO, HIREDATE, SYSDATE FROM EMP
WHERE ADD_MONTHS(HIREDATE,40*12)>SYSDATE;

-- MONTHS_BETWEEN(날짜,날짜)
SELECT EMPNO, ENAME, HIREDATE, SYSDATE FROM EMP;
SELECT EMPNO, ENAME, HIREDATE, SYSDATE,
       trunc(MONTHS_BETWEEN(SYSDATE,HIREDATE)/12) AS 근속년수
FROM EMP;


SELECT SYSDATE,
       NEXT_DAY(SYSDATE,'월요일'),
       LAST_DAY(SYSDATE)
FROM DUAL;

