--1¹®
SELECT * FROM EMP
WHERE ENAME LIKE '%S';

--2¹®
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';

--3¹®
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE SAL > 2000 AND DEPTNO IN(20,30);

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE SAL > 2000 AND DEPTNO =20
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE SAL > 2000 AND DEPTNO =30;

--4ANS
SELECT * FROM EMP
WHERE SAL <= 2000 OR SAL >= 3000;

--5ANS
SELECT ENAME, EMPNO, SAL, DEPTNO FROM EMP
WHERE ENAME LIKE '%E%' AND 
           DEPTNO = 30 AND
           SAL NOT BETWEEN 1000 AND 2000; 
           
-- 6ANS
--SELECT * FROM EMP;
SELECT * FROM EMP
WHERE COMM IS NULL AND
          JOB IN ('MANAGER','CLERK') AND
          ENAME NOT LIKE '_L%';

